[project]
name = "toolbox-llamaindex"
dynamic = ["version"]
readme = "README.md"
description = "Python SDK for interacting with the Toolbox service with LlamaIndex"
license = {file = "LICENSE"}
requires-python = ">=3.10"
authors = [
    {name = "Google LLC", email = "googleapis-packages@google.com"}
]
dependencies = [
    "toolbox-core==0.5.9",
    "llama-index-core>=0.12.0,<1.0.0",
    "PyYAML>=6.0.1,<7.0.0",
    "pydantic>=2.8.0,<3.0.0",
    "aiohttp>=3.8.6,<4.0.0",
    "deprecated>=1.2.10,<2.0.0",
]

classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

# Tells setuptools that packages are under the 'src' directory
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "toolbox_llamaindex.version.__version__"}

[project.urls]
Homepage = "https://github.com/googleapis/mcp-toolbox-sdk-python/blob/main/packages/toolbox-llamaindex"
Repository = "https://github.com/googleapis/mcp-toolbox-sdk-python.git"
"Bug Tracker" = "https://github.com/googleapis/mcp-toolbox-sdk-python/issues"
Changelog = "https://github.com/googleapis/mcp-toolbox-sdk-python/blob/main/packages/toolbox-llamaindex/CHANGELOG.md"

[project.optional-dependencies]
test = [
    "black[jupyter]==26.1.0",
    "isort==7.0.0",
    "mypy==1.19.1",
    "pytest-asyncio==1.3.0",
    "pytest==9.0.2",
    "pytest-cov==7.0.0",
    "Pillow==12.1.1; python_version >= '3.10'",
    "google-cloud-secret-manager==2.26.0",
    "google-cloud-storage==3.9.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
disallow_incomplete_defs = true
